[package]
name = "rustre-parser"
description = "Lustre v6 parser"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/elegaanz/rustre"

[dependencies]
logos = "0.12.1"
rowan = "0.15.5"