image: nixos/nix:latest

pages:
    script:
    - nix develop -c 'mdbook build -d public'
    - nix develop -c 'typst report/main.typ public/report.pdf'
    artifacts:
        paths:
        - public
    only:
        variables:
        - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
