image: peaceiris/mdbook:latest

pages:
    script:
    - apk add bash
    - mdbook build --d public
    artifacts:
        paths:
        - public
    only:
        variables:
        - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
