image: nixos/nix:latest

pages:
    script:
    - nix-shell --run 'mdbook build -d public'
    artifacts:
        paths:
        - public
    only:
        variables:
        - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
