image: nixos/nix:latest

pages:
    script:
    - nix --extra-experimental-features nix-command develop --extra-experimental-features flakes -c mdbook build -d public
    - nix --extra-experimental-features nix-command develop --extra-experimental-features flakes -c typst report/main.typ public/report.pdf
    artifacts:
        paths:
        - public
    only:
        variables:
        - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
