[book]
authors = ["Ana Gelez"]
language = "en"
multilingual = false
src = "src"
title = "Rustre"

[preprocessor.git-links]
command = 'python gitlinks.py'

[preprocessor.plantuml]
plantuml-cmd="https://www.plantuml.com/plantuml"
use-data-uris=true
