[package]
name = "rustre-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
petgraph = "0.6.2"
rustre-parser = { path = "../rustre-parser" }
yeter = "0.4.0"
